/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as modulesProfileRoutesProfileDotrouteRouteImport } from './modules/profile/routes/profile.route'
import { Route as modulesGithubImportRoutesImportDotrouteRouteImport } from './modules/github-import/routes/import.route'
import { Route as modulesHomeRoutesIndexDotrouteRouteImport } from './modules/home/routes/index.route'
import { Route as modulesProfileRoutesProfileDotusernameDotrouteRouteImport } from './modules/profile/routes/profile.$username.route'
import { Route as modulesGithubImportRoutesImportDotgithubDotrouteRouteImport } from './modules/github-import/routes/import.github.route'
import { Route as modulesRepositoriesRoutesRepositoryDotusernameDotslugDotrouteRouteImport } from './modules/repositories/routes/repository.$username.$slug.route'
import { Route as modulesAuthRoutesApiDotauthDotDotrouteRouteImport } from './modules/auth/routes/api.auth.$.route'
import { Route as modulesRepositoriesRoutesRepositoryDotusernameDotslugDotcommitsDotrefDotrouteRouteImport } from './modules/repositories/routes/repository.$username.$slug.commits.$ref.route'
import { Route as modulesRepositoriesRoutesRepositoryDotusernameDotslugDottreeDotrefDotDotrouteRouteImport } from './modules/repositories/routes/repository.$username.$slug.tree.$ref.$.route'
import { Route as modulesRepositoriesRoutesRepositoryDotusernameDotslugDotblobDotrefDotDotrouteRouteImport } from './modules/repositories/routes/repository.$username.$slug.blob.$ref.$.route'

const modulesProfileRoutesProfileDotrouteRoute =
  modulesProfileRoutesProfileDotrouteRouteImport.update({
    id: '/profile',
    path: '/profile',
    getParentRoute: () => rootRouteImport,
  } as any)
const modulesGithubImportRoutesImportDotrouteRoute =
  modulesGithubImportRoutesImportDotrouteRouteImport.update({
    id: '/import',
    path: '/import',
    getParentRoute: () => rootRouteImport,
  } as any)
const modulesHomeRoutesIndexDotrouteRoute =
  modulesHomeRoutesIndexDotrouteRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => rootRouteImport,
  } as any)
const modulesProfileRoutesProfileDotusernameDotrouteRoute =
  modulesProfileRoutesProfileDotusernameDotrouteRouteImport.update({
    id: '/$username',
    path: '/$username',
    getParentRoute: () => modulesProfileRoutesProfileDotrouteRoute,
  } as any)
const modulesGithubImportRoutesImportDotgithubDotrouteRoute =
  modulesGithubImportRoutesImportDotgithubDotrouteRouteImport.update({
    id: '/github',
    path: '/github',
    getParentRoute: () => modulesGithubImportRoutesImportDotrouteRoute,
  } as any)
const modulesRepositoriesRoutesRepositoryDotusernameDotslugDotrouteRoute =
  modulesRepositoriesRoutesRepositoryDotusernameDotslugDotrouteRouteImport.update(
    {
      id: '/$username/$slug',
      path: '/$username/$slug',
      getParentRoute: () => rootRouteImport,
    } as any,
  )
const modulesAuthRoutesApiDotauthDotDotrouteRoute =
  modulesAuthRoutesApiDotauthDotDotrouteRouteImport.update({
    id: '/api/auth/$',
    path: '/api/auth/$',
    getParentRoute: () => rootRouteImport,
  } as any)
const modulesRepositoriesRoutesRepositoryDotusernameDotslugDotcommitsDotrefDotrouteRoute =
  modulesRepositoriesRoutesRepositoryDotusernameDotslugDotcommitsDotrefDotrouteRouteImport.update(
    {
      id: '/$username/$slug/commits/$ref',
      path: '/$username/$slug/commits/$ref',
      getParentRoute: () => rootRouteImport,
    } as any,
  )
const modulesRepositoriesRoutesRepositoryDotusernameDotslugDottreeDotrefDotDotrouteRoute =
  modulesRepositoriesRoutesRepositoryDotusernameDotslugDottreeDotrefDotDotrouteRouteImport.update(
    {
      id: '/$username/$slug/tree/$ref/$',
      path: '/$username/$slug/tree/$ref/$',
      getParentRoute: () => rootRouteImport,
    } as any,
  )
const modulesRepositoriesRoutesRepositoryDotusernameDotslugDotblobDotrefDotDotrouteRoute =
  modulesRepositoriesRoutesRepositoryDotusernameDotslugDotblobDotrefDotDotrouteRouteImport.update(
    {
      id: '/$username/$slug/blob/$ref/$',
      path: '/$username/$slug/blob/$ref/$',
      getParentRoute: () => rootRouteImport,
    } as any,
  )

export interface FileRoutesByFullPath {
  '/': typeof modulesHomeRoutesIndexDotrouteRoute
  '/import': typeof modulesGithubImportRoutesImportDotrouteRouteWithChildren
  '/profile': typeof modulesProfileRoutesProfileDotrouteRouteWithChildren
  '/$username/$slug': typeof modulesRepositoriesRoutesRepositoryDotusernameDotslugDotrouteRoute
  '/import/github': typeof modulesGithubImportRoutesImportDotgithubDotrouteRoute
  '/profile/$username': typeof modulesProfileRoutesProfileDotusernameDotrouteRoute
  '/api/auth/$': typeof modulesAuthRoutesApiDotauthDotDotrouteRoute
  '/$username/$slug/commits/$ref': typeof modulesRepositoriesRoutesRepositoryDotusernameDotslugDotcommitsDotrefDotrouteRoute
  '/$username/$slug/blob/$ref/$': typeof modulesRepositoriesRoutesRepositoryDotusernameDotslugDotblobDotrefDotDotrouteRoute
  '/$username/$slug/tree/$ref/$': typeof modulesRepositoriesRoutesRepositoryDotusernameDotslugDottreeDotrefDotDotrouteRoute
}
export interface FileRoutesByTo {
  '/': typeof modulesHomeRoutesIndexDotrouteRoute
  '/import': typeof modulesGithubImportRoutesImportDotrouteRouteWithChildren
  '/profile': typeof modulesProfileRoutesProfileDotrouteRouteWithChildren
  '/$username/$slug': typeof modulesRepositoriesRoutesRepositoryDotusernameDotslugDotrouteRoute
  '/import/github': typeof modulesGithubImportRoutesImportDotgithubDotrouteRoute
  '/profile/$username': typeof modulesProfileRoutesProfileDotusernameDotrouteRoute
  '/api/auth/$': typeof modulesAuthRoutesApiDotauthDotDotrouteRoute
  '/$username/$slug/commits/$ref': typeof modulesRepositoriesRoutesRepositoryDotusernameDotslugDotcommitsDotrefDotrouteRoute
  '/$username/$slug/blob/$ref/$': typeof modulesRepositoriesRoutesRepositoryDotusernameDotslugDotblobDotrefDotDotrouteRoute
  '/$username/$slug/tree/$ref/$': typeof modulesRepositoriesRoutesRepositoryDotusernameDotslugDottreeDotrefDotDotrouteRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof modulesHomeRoutesIndexDotrouteRoute
  '/import': typeof modulesGithubImportRoutesImportDotrouteRouteWithChildren
  '/profile': typeof modulesProfileRoutesProfileDotrouteRouteWithChildren
  '/$username/$slug': typeof modulesRepositoriesRoutesRepositoryDotusernameDotslugDotrouteRoute
  '/import/github': typeof modulesGithubImportRoutesImportDotgithubDotrouteRoute
  '/profile/$username': typeof modulesProfileRoutesProfileDotusernameDotrouteRoute
  '/api/auth/$': typeof modulesAuthRoutesApiDotauthDotDotrouteRoute
  '/$username/$slug/commits/$ref': typeof modulesRepositoriesRoutesRepositoryDotusernameDotslugDotcommitsDotrefDotrouteRoute
  '/$username/$slug/blob/$ref/$': typeof modulesRepositoriesRoutesRepositoryDotusernameDotslugDotblobDotrefDotDotrouteRoute
  '/$username/$slug/tree/$ref/$': typeof modulesRepositoriesRoutesRepositoryDotusernameDotslugDottreeDotrefDotDotrouteRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/import'
    | '/profile'
    | '/$username/$slug'
    | '/import/github'
    | '/profile/$username'
    | '/api/auth/$'
    | '/$username/$slug/commits/$ref'
    | '/$username/$slug/blob/$ref/$'
    | '/$username/$slug/tree/$ref/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/import'
    | '/profile'
    | '/$username/$slug'
    | '/import/github'
    | '/profile/$username'
    | '/api/auth/$'
    | '/$username/$slug/commits/$ref'
    | '/$username/$slug/blob/$ref/$'
    | '/$username/$slug/tree/$ref/$'
  id:
    | '__root__'
    | '/'
    | '/import'
    | '/profile'
    | '/$username/$slug'
    | '/import/github'
    | '/profile/$username'
    | '/api/auth/$'
    | '/$username/$slug/commits/$ref'
    | '/$username/$slug/blob/$ref/$'
    | '/$username/$slug/tree/$ref/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  modulesHomeRoutesIndexDotrouteRoute: typeof modulesHomeRoutesIndexDotrouteRoute
  modulesGithubImportRoutesImportDotrouteRoute: typeof modulesGithubImportRoutesImportDotrouteRouteWithChildren
  modulesProfileRoutesProfileDotrouteRoute: typeof modulesProfileRoutesProfileDotrouteRouteWithChildren
  modulesRepositoriesRoutesRepositoryDotusernameDotslugDotrouteRoute: typeof modulesRepositoriesRoutesRepositoryDotusernameDotslugDotrouteRoute
  modulesAuthRoutesApiDotauthDotDotrouteRoute: typeof modulesAuthRoutesApiDotauthDotDotrouteRoute
  modulesRepositoriesRoutesRepositoryDotusernameDotslugDotcommitsDotrefDotrouteRoute: typeof modulesRepositoriesRoutesRepositoryDotusernameDotslugDotcommitsDotrefDotrouteRoute
  modulesRepositoriesRoutesRepositoryDotusernameDotslugDotblobDotrefDotDotrouteRoute: typeof modulesRepositoriesRoutesRepositoryDotusernameDotslugDotblobDotrefDotDotrouteRoute
  modulesRepositoriesRoutesRepositoryDotusernameDotslugDottreeDotrefDotDotrouteRoute: typeof modulesRepositoriesRoutesRepositoryDotusernameDotslugDottreeDotrefDotDotrouteRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof modulesProfileRoutesProfileDotrouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/import': {
      id: '/import'
      path: '/import'
      fullPath: '/import'
      preLoaderRoute: typeof modulesGithubImportRoutesImportDotrouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof modulesHomeRoutesIndexDotrouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/$username': {
      id: '/profile/$username'
      path: '/$username'
      fullPath: '/profile/$username'
      preLoaderRoute: typeof modulesProfileRoutesProfileDotusernameDotrouteRouteImport
      parentRoute: typeof modulesProfileRoutesProfileDotrouteRoute
    }
    '/import/github': {
      id: '/import/github'
      path: '/github'
      fullPath: '/import/github'
      preLoaderRoute: typeof modulesGithubImportRoutesImportDotgithubDotrouteRouteImport
      parentRoute: typeof modulesGithubImportRoutesImportDotrouteRoute
    }
    '/$username/$slug': {
      id: '/$username/$slug'
      path: '/$username/$slug'
      fullPath: '/$username/$slug'
      preLoaderRoute: typeof modulesRepositoriesRoutesRepositoryDotusernameDotslugDotrouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof modulesAuthRoutesApiDotauthDotDotrouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$username/$slug/commits/$ref': {
      id: '/$username/$slug/commits/$ref'
      path: '/$username/$slug/commits/$ref'
      fullPath: '/$username/$slug/commits/$ref'
      preLoaderRoute: typeof modulesRepositoriesRoutesRepositoryDotusernameDotslugDotcommitsDotrefDotrouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$username/$slug/tree/$ref/$': {
      id: '/$username/$slug/tree/$ref/$'
      path: '/$username/$slug/tree/$ref/$'
      fullPath: '/$username/$slug/tree/$ref/$'
      preLoaderRoute: typeof modulesRepositoriesRoutesRepositoryDotusernameDotslugDottreeDotrefDotDotrouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$username/$slug/blob/$ref/$': {
      id: '/$username/$slug/blob/$ref/$'
      path: '/$username/$slug/blob/$ref/$'
      fullPath: '/$username/$slug/blob/$ref/$'
      preLoaderRoute: typeof modulesRepositoriesRoutesRepositoryDotusernameDotslugDotblobDotrefDotDotrouteRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface modulesGithubImportRoutesImportDotrouteRouteChildren {
  modulesGithubImportRoutesImportDotgithubDotrouteRoute: typeof modulesGithubImportRoutesImportDotgithubDotrouteRoute
}

const modulesGithubImportRoutesImportDotrouteRouteChildren: modulesGithubImportRoutesImportDotrouteRouteChildren =
  {
    modulesGithubImportRoutesImportDotgithubDotrouteRoute:
      modulesGithubImportRoutesImportDotgithubDotrouteRoute,
  }

const modulesGithubImportRoutesImportDotrouteRouteWithChildren =
  modulesGithubImportRoutesImportDotrouteRoute._addFileChildren(
    modulesGithubImportRoutesImportDotrouteRouteChildren,
  )

interface modulesProfileRoutesProfileDotrouteRouteChildren {
  modulesProfileRoutesProfileDotusernameDotrouteRoute: typeof modulesProfileRoutesProfileDotusernameDotrouteRoute
}

const modulesProfileRoutesProfileDotrouteRouteChildren: modulesProfileRoutesProfileDotrouteRouteChildren =
  {
    modulesProfileRoutesProfileDotusernameDotrouteRoute:
      modulesProfileRoutesProfileDotusernameDotrouteRoute,
  }

const modulesProfileRoutesProfileDotrouteRouteWithChildren =
  modulesProfileRoutesProfileDotrouteRoute._addFileChildren(
    modulesProfileRoutesProfileDotrouteRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  modulesHomeRoutesIndexDotrouteRoute: modulesHomeRoutesIndexDotrouteRoute,
  modulesGithubImportRoutesImportDotrouteRoute:
    modulesGithubImportRoutesImportDotrouteRouteWithChildren,
  modulesProfileRoutesProfileDotrouteRoute:
    modulesProfileRoutesProfileDotrouteRouteWithChildren,
  modulesRepositoriesRoutesRepositoryDotusernameDotslugDotrouteRoute:
    modulesRepositoriesRoutesRepositoryDotusernameDotslugDotrouteRoute,
  modulesAuthRoutesApiDotauthDotDotrouteRoute:
    modulesAuthRoutesApiDotauthDotDotrouteRoute,
  modulesRepositoriesRoutesRepositoryDotusernameDotslugDotcommitsDotrefDotrouteRoute:
    modulesRepositoriesRoutesRepositoryDotusernameDotslugDotcommitsDotrefDotrouteRoute,
  modulesRepositoriesRoutesRepositoryDotusernameDotslugDotblobDotrefDotDotrouteRoute:
    modulesRepositoriesRoutesRepositoryDotusernameDotslugDotblobDotrefDotDotrouteRoute,
  modulesRepositoriesRoutesRepositoryDotusernameDotslugDottreeDotrefDotDotrouteRoute:
    modulesRepositoriesRoutesRepositoryDotusernameDotslugDottreeDotrefDotDotrouteRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
