/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as modulesProfileRoutesProfileDotrouteRouteImport } from './modules/profile/routes/profile.route'
import { Route as modulesHomeRoutesIndexDotrouteRouteImport } from './modules/home/routes/index.route'
import { Route as modulesProfileRoutesProfileDotusernameDotrouteRouteImport } from './modules/profile/routes/profile.$username.route'
import { Route as modulesRepositoriesRoutesRepositoryDotusernameDotslugDotrouteRouteImport } from './modules/repositories/routes/repository.$username.$slug.route'
import { Route as modulesAuthRoutesApiDotauthDotDotrouteRouteImport } from './modules/auth/routes/api.auth.$.route'

const modulesProfileRoutesProfileDotrouteRoute =
  modulesProfileRoutesProfileDotrouteRouteImport.update({
    id: '/profile',
    path: '/profile',
    getParentRoute: () => rootRouteImport,
  } as any)
const modulesHomeRoutesIndexDotrouteRoute =
  modulesHomeRoutesIndexDotrouteRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => rootRouteImport,
  } as any)
const modulesProfileRoutesProfileDotusernameDotrouteRoute =
  modulesProfileRoutesProfileDotusernameDotrouteRouteImport.update({
    id: '/$username',
    path: '/$username',
    getParentRoute: () => modulesProfileRoutesProfileDotrouteRoute,
  } as any)
const modulesRepositoriesRoutesRepositoryDotusernameDotslugDotrouteRoute =
  modulesRepositoriesRoutesRepositoryDotusernameDotslugDotrouteRouteImport.update(
    {
      id: '/$username/$slug',
      path: '/$username/$slug',
      getParentRoute: () => rootRouteImport,
    } as any,
  )
const modulesAuthRoutesApiDotauthDotDotrouteRoute =
  modulesAuthRoutesApiDotauthDotDotrouteRouteImport.update({
    id: '/api/auth/$',
    path: '/api/auth/$',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof modulesHomeRoutesIndexDotrouteRoute
  '/profile': typeof modulesProfileRoutesProfileDotrouteRouteWithChildren
  '/$username/$slug': typeof modulesRepositoriesRoutesRepositoryDotusernameDotslugDotrouteRoute
  '/profile/$username': typeof modulesProfileRoutesProfileDotusernameDotrouteRoute
  '/api/auth/$': typeof modulesAuthRoutesApiDotauthDotDotrouteRoute
}
export interface FileRoutesByTo {
  '/': typeof modulesHomeRoutesIndexDotrouteRoute
  '/profile': typeof modulesProfileRoutesProfileDotrouteRouteWithChildren
  '/$username/$slug': typeof modulesRepositoriesRoutesRepositoryDotusernameDotslugDotrouteRoute
  '/profile/$username': typeof modulesProfileRoutesProfileDotusernameDotrouteRoute
  '/api/auth/$': typeof modulesAuthRoutesApiDotauthDotDotrouteRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof modulesHomeRoutesIndexDotrouteRoute
  '/profile': typeof modulesProfileRoutesProfileDotrouteRouteWithChildren
  '/$username/$slug': typeof modulesRepositoriesRoutesRepositoryDotusernameDotslugDotrouteRoute
  '/profile/$username': typeof modulesProfileRoutesProfileDotusernameDotrouteRoute
  '/api/auth/$': typeof modulesAuthRoutesApiDotauthDotDotrouteRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/profile'
    | '/$username/$slug'
    | '/profile/$username'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/profile'
    | '/$username/$slug'
    | '/profile/$username'
    | '/api/auth/$'
  id:
    | '__root__'
    | '/'
    | '/profile'
    | '/$username/$slug'
    | '/profile/$username'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  modulesHomeRoutesIndexDotrouteRoute: typeof modulesHomeRoutesIndexDotrouteRoute
  modulesProfileRoutesProfileDotrouteRoute: typeof modulesProfileRoutesProfileDotrouteRouteWithChildren
  modulesRepositoriesRoutesRepositoryDotusernameDotslugDotrouteRoute: typeof modulesRepositoriesRoutesRepositoryDotusernameDotslugDotrouteRoute
  modulesAuthRoutesApiDotauthDotDotrouteRoute: typeof modulesAuthRoutesApiDotauthDotDotrouteRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof modulesProfileRoutesProfileDotrouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof modulesHomeRoutesIndexDotrouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/$username': {
      id: '/profile/$username'
      path: '/$username'
      fullPath: '/profile/$username'
      preLoaderRoute: typeof modulesProfileRoutesProfileDotusernameDotrouteRouteImport
      parentRoute: typeof modulesProfileRoutesProfileDotrouteRoute
    }
    '/$username/$slug': {
      id: '/$username/$slug'
      path: '/$username/$slug'
      fullPath: '/$username/$slug'
      preLoaderRoute: typeof modulesRepositoriesRoutesRepositoryDotusernameDotslugDotrouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof modulesAuthRoutesApiDotauthDotDotrouteRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface modulesProfileRoutesProfileDotrouteRouteChildren {
  modulesProfileRoutesProfileDotusernameDotrouteRoute: typeof modulesProfileRoutesProfileDotusernameDotrouteRoute
}

const modulesProfileRoutesProfileDotrouteRouteChildren: modulesProfileRoutesProfileDotrouteRouteChildren =
  {
    modulesProfileRoutesProfileDotusernameDotrouteRoute:
      modulesProfileRoutesProfileDotusernameDotrouteRoute,
  }

const modulesProfileRoutesProfileDotrouteRouteWithChildren =
  modulesProfileRoutesProfileDotrouteRoute._addFileChildren(
    modulesProfileRoutesProfileDotrouteRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  modulesHomeRoutesIndexDotrouteRoute: modulesHomeRoutesIndexDotrouteRoute,
  modulesProfileRoutesProfileDotrouteRoute:
    modulesProfileRoutesProfileDotrouteRouteWithChildren,
  modulesRepositoriesRoutesRepositoryDotusernameDotslugDotrouteRoute:
    modulesRepositoriesRoutesRepositoryDotusernameDotslugDotrouteRoute,
  modulesAuthRoutesApiDotauthDotDotrouteRoute:
    modulesAuthRoutesApiDotauthDotDotrouteRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
