/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as modulesProfileRoutesProfileDotrouteRouteImport } from './modules/profile/routes/profile.route'
import { Route as modulesGithubImportRoutesImportDotrouteRouteImport } from './modules/github-import/routes/import.route'
import { Route as modulesHomeRoutesIndexDotrouteRouteImport } from './modules/home/routes/index.route'
import { Route as modulesProfileRoutesProfileDotusernameDotrouteRouteImport } from './modules/profile/routes/profile.$username.route'
import { Route as modulesGithubImportRoutesImportDotgithubDotrouteRouteImport } from './modules/github-import/routes/import.github.route'
import { Route as modulesRepositoriesRoutesRepositoryDotusernameDotslugDotrouteRouteImport } from './modules/repositories/routes/repository.$username.$slug.route'
import { Route as modulesAuthRoutesApiDotauthDotDotrouteRouteImport } from './modules/auth/routes/api.auth.$.route'
import { Route as modulesPullRequestsRoutesRepositoryDotusernameDotslugDotpullsDotrouteRouteImport } from './modules/pull-requests/routes/repository.$username.$slug.pulls.route'
import { Route as modulesRepositoryCollaboratorsRoutesRepositoryDotusernameDotslugDotsettingsDotcollaboratorsDotrouteRouteImport } from './modules/repository-collaborators/routes/repository.$username.$slug.settings.collaborators.route'
import { Route as modulesBranchProtectionRoutesRepositoryDotusernameDotslugDotsettingsDotbranchProtectionDotrouteRouteImport } from './modules/branch-protection/routes/repository.$username.$slug.settings.branch-protection.route'
import { Route as modulesCheckStatusesRoutesRepositoryDotusernameDotslugDotsettingsDotstatusProvidersDotrouteRouteImport } from './modules/check-statuses/routes/repository.$username.$slug.settings.status-providers.route'
import { Route as modulesPullRequestsRoutesRepositoryDotusernameDotslugDotpullsDotnewDotrouteRouteImport } from './modules/pull-requests/routes/repository.$username.$slug.pulls.new.route'
import { Route as modulesPullRequestsRoutesRepositoryDotusernameDotslugDotpullsDotnumberDotrouteRouteImport } from './modules/pull-requests/routes/repository.$username.$slug.pulls.$number.route'
import { Route as modulesRepositoriesRoutesRepositoryDotusernameDotslugDotcommitsDotrefDotrouteRouteImport } from './modules/repositories/routes/repository.$username.$slug.commits.$ref.route'
import { Route as modulesRepositoriesRoutesRepositoryDotusernameDotslugDottreeDotrefDotDotrouteRouteImport } from './modules/repositories/routes/repository.$username.$slug.tree.$ref.$.route'
import { Route as modulesPullRequestsRoutesRepositoryDotusernameDotslugDotpullsDotnumberDotfilesDotrouteRouteImport } from './modules/pull-requests/routes/repository.$username.$slug.pulls.$number.files.route'
import { Route as modulesPullRequestsRoutesRepositoryDotusernameDotslugDotpullsDotnumberDotcommitsDotrouteRouteImport } from './modules/pull-requests/routes/repository.$username.$slug.pulls.$number.commits.route'
import { Route as modulesRepositoriesRoutesRepositoryDotusernameDotslugDotblobDotrefDotDotrouteRouteImport } from './modules/repositories/routes/repository.$username.$slug.blob.$ref.$.route'

const modulesProfileRoutesProfileDotrouteRoute =
  modulesProfileRoutesProfileDotrouteRouteImport.update({
    id: '/profile',
    path: '/profile',
    getParentRoute: () => rootRouteImport,
  } as any)
const modulesGithubImportRoutesImportDotrouteRoute =
  modulesGithubImportRoutesImportDotrouteRouteImport.update({
    id: '/import',
    path: '/import',
    getParentRoute: () => rootRouteImport,
  } as any)
const modulesHomeRoutesIndexDotrouteRoute =
  modulesHomeRoutesIndexDotrouteRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => rootRouteImport,
  } as any)
const modulesProfileRoutesProfileDotusernameDotrouteRoute =
  modulesProfileRoutesProfileDotusernameDotrouteRouteImport.update({
    id: '/$username',
    path: '/$username',
    getParentRoute: () => modulesProfileRoutesProfileDotrouteRoute,
  } as any)
const modulesGithubImportRoutesImportDotgithubDotrouteRoute =
  modulesGithubImportRoutesImportDotgithubDotrouteRouteImport.update({
    id: '/github',
    path: '/github',
    getParentRoute: () => modulesGithubImportRoutesImportDotrouteRoute,
  } as any)
const modulesRepositoriesRoutesRepositoryDotusernameDotslugDotrouteRoute =
  modulesRepositoriesRoutesRepositoryDotusernameDotslugDotrouteRouteImport.update(
    {
      id: '/$username/$slug',
      path: '/$username/$slug',
      getParentRoute: () => rootRouteImport,
    } as any,
  )
const modulesAuthRoutesApiDotauthDotDotrouteRoute =
  modulesAuthRoutesApiDotauthDotDotrouteRouteImport.update({
    id: '/api/auth/$',
    path: '/api/auth/$',
    getParentRoute: () => rootRouteImport,
  } as any)
const modulesPullRequestsRoutesRepositoryDotusernameDotslugDotpullsDotrouteRoute =
  modulesPullRequestsRoutesRepositoryDotusernameDotslugDotpullsDotrouteRouteImport.update(
    {
      id: '/$username/$slug/pulls',
      path: '/$username/$slug/pulls',
      getParentRoute: () => rootRouteImport,
    } as any,
  )
const modulesRepositoryCollaboratorsRoutesRepositoryDotusernameDotslugDotsettingsDotcollaboratorsDotrouteRoute =
  modulesRepositoryCollaboratorsRoutesRepositoryDotusernameDotslugDotsettingsDotcollaboratorsDotrouteRouteImport.update(
    {
      id: '/$username/$slug/settings/collaborators',
      path: '/$username/$slug/settings/collaborators',
      getParentRoute: () => rootRouteImport,
    } as any,
  )
const modulesBranchProtectionRoutesRepositoryDotusernameDotslugDotsettingsDotbranchProtectionDotrouteRoute =
  modulesBranchProtectionRoutesRepositoryDotusernameDotslugDotsettingsDotbranchProtectionDotrouteRouteImport.update(
    {
      id: '/$username/$slug/settings/branch-protection',
      path: '/$username/$slug/settings/branch-protection',
      getParentRoute: () => rootRouteImport,
    } as any,
  )
const modulesCheckStatusesRoutesRepositoryDotusernameDotslugDotsettingsDotstatusProvidersDotrouteRoute =
  modulesCheckStatusesRoutesRepositoryDotusernameDotslugDotsettingsDotstatusProvidersDotrouteRouteImport.update(
    {
      id: '/$username/$slug/settings/status-providers',
      path: '/$username/$slug/settings/status-providers',
      getParentRoute: () => rootRouteImport,
    } as any,
  )
const modulesPullRequestsRoutesRepositoryDotusernameDotslugDotpullsDotnewDotrouteRoute =
  modulesPullRequestsRoutesRepositoryDotusernameDotslugDotpullsDotnewDotrouteRouteImport.update(
    {
      id: '/$username/$slug/pulls/new',
      path: '/$username/$slug/pulls/new',
      getParentRoute: () => rootRouteImport,
    } as any,
  )
const modulesPullRequestsRoutesRepositoryDotusernameDotslugDotpullsDotnumberDotrouteRoute =
  modulesPullRequestsRoutesRepositoryDotusernameDotslugDotpullsDotnumberDotrouteRouteImport.update(
    {
      id: '/$username/$slug/pulls/$number',
      path: '/$username/$slug/pulls/$number',
      getParentRoute: () => rootRouteImport,
    } as any,
  )
const modulesRepositoriesRoutesRepositoryDotusernameDotslugDotcommitsDotrefDotrouteRoute =
  modulesRepositoriesRoutesRepositoryDotusernameDotslugDotcommitsDotrefDotrouteRouteImport.update(
    {
      id: '/$username/$slug/commits/$ref',
      path: '/$username/$slug/commits/$ref',
      getParentRoute: () => rootRouteImport,
    } as any,
  )
const modulesRepositoriesRoutesRepositoryDotusernameDotslugDottreeDotrefDotDotrouteRoute =
  modulesRepositoriesRoutesRepositoryDotusernameDotslugDottreeDotrefDotDotrouteRouteImport.update(
    {
      id: '/$username/$slug/tree/$ref/$',
      path: '/$username/$slug/tree/$ref/$',
      getParentRoute: () => rootRouteImport,
    } as any,
  )
const modulesPullRequestsRoutesRepositoryDotusernameDotslugDotpullsDotnumberDotfilesDotrouteRoute =
  modulesPullRequestsRoutesRepositoryDotusernameDotslugDotpullsDotnumberDotfilesDotrouteRouteImport.update(
    {
      id: '/$username/$slug/pulls/$number/files',
      path: '/$username/$slug/pulls/$number/files',
      getParentRoute: () => rootRouteImport,
    } as any,
  )
const modulesPullRequestsRoutesRepositoryDotusernameDotslugDotpullsDotnumberDotcommitsDotrouteRoute =
  modulesPullRequestsRoutesRepositoryDotusernameDotslugDotpullsDotnumberDotcommitsDotrouteRouteImport.update(
    {
      id: '/$username/$slug/pulls/$number/commits',
      path: '/$username/$slug/pulls/$number/commits',
      getParentRoute: () => rootRouteImport,
    } as any,
  )
const modulesRepositoriesRoutesRepositoryDotusernameDotslugDotblobDotrefDotDotrouteRoute =
  modulesRepositoriesRoutesRepositoryDotusernameDotslugDotblobDotrefDotDotrouteRouteImport.update(
    {
      id: '/$username/$slug/blob/$ref/$',
      path: '/$username/$slug/blob/$ref/$',
      getParentRoute: () => rootRouteImport,
    } as any,
  )

export interface FileRoutesByFullPath {
  '/': typeof modulesHomeRoutesIndexDotrouteRoute
  '/import': typeof modulesGithubImportRoutesImportDotrouteRouteWithChildren
  '/profile': typeof modulesProfileRoutesProfileDotrouteRouteWithChildren
  '/$username/$slug': typeof modulesRepositoriesRoutesRepositoryDotusernameDotslugDotrouteRoute
  '/import/github': typeof modulesGithubImportRoutesImportDotgithubDotrouteRoute
  '/profile/$username': typeof modulesProfileRoutesProfileDotusernameDotrouteRoute
  '/$username/$slug/pulls': typeof modulesPullRequestsRoutesRepositoryDotusernameDotslugDotpullsDotrouteRoute
  '/api/auth/$': typeof modulesAuthRoutesApiDotauthDotDotrouteRoute
  '/$username/$slug/commits/$ref': typeof modulesRepositoriesRoutesRepositoryDotusernameDotslugDotcommitsDotrefDotrouteRoute
  '/$username/$slug/pulls/$number': typeof modulesPullRequestsRoutesRepositoryDotusernameDotslugDotpullsDotnumberDotrouteRoute
  '/$username/$slug/pulls/new': typeof modulesPullRequestsRoutesRepositoryDotusernameDotslugDotpullsDotnewDotrouteRoute
  '/$username/$slug/settings/branch-protection': typeof modulesBranchProtectionRoutesRepositoryDotusernameDotslugDotsettingsDotbranchProtectionDotrouteRoute
  '/$username/$slug/settings/status-providers': typeof modulesCheckStatusesRoutesRepositoryDotusernameDotslugDotsettingsDotstatusProvidersDotrouteRoute
  '/$username/$slug/settings/collaborators': typeof modulesRepositoryCollaboratorsRoutesRepositoryDotusernameDotslugDotsettingsDotcollaboratorsDotrouteRoute
  '/$username/$slug/blob/$ref/$': typeof modulesRepositoriesRoutesRepositoryDotusernameDotslugDotblobDotrefDotDotrouteRoute
  '/$username/$slug/pulls/$number/commits': typeof modulesPullRequestsRoutesRepositoryDotusernameDotslugDotpullsDotnumberDotcommitsDotrouteRoute
  '/$username/$slug/pulls/$number/files': typeof modulesPullRequestsRoutesRepositoryDotusernameDotslugDotpullsDotnumberDotfilesDotrouteRoute
  '/$username/$slug/tree/$ref/$': typeof modulesRepositoriesRoutesRepositoryDotusernameDotslugDottreeDotrefDotDotrouteRoute
}
export interface FileRoutesByTo {
  '/': typeof modulesHomeRoutesIndexDotrouteRoute
  '/import': typeof modulesGithubImportRoutesImportDotrouteRouteWithChildren
  '/profile': typeof modulesProfileRoutesProfileDotrouteRouteWithChildren
  '/$username/$slug': typeof modulesRepositoriesRoutesRepositoryDotusernameDotslugDotrouteRoute
  '/import/github': typeof modulesGithubImportRoutesImportDotgithubDotrouteRoute
  '/profile/$username': typeof modulesProfileRoutesProfileDotusernameDotrouteRoute
  '/$username/$slug/pulls': typeof modulesPullRequestsRoutesRepositoryDotusernameDotslugDotpullsDotrouteRoute
  '/api/auth/$': typeof modulesAuthRoutesApiDotauthDotDotrouteRoute
  '/$username/$slug/commits/$ref': typeof modulesRepositoriesRoutesRepositoryDotusernameDotslugDotcommitsDotrefDotrouteRoute
  '/$username/$slug/pulls/$number': typeof modulesPullRequestsRoutesRepositoryDotusernameDotslugDotpullsDotnumberDotrouteRoute
  '/$username/$slug/pulls/new': typeof modulesPullRequestsRoutesRepositoryDotusernameDotslugDotpullsDotnewDotrouteRoute
  '/$username/$slug/settings/branch-protection': typeof modulesBranchProtectionRoutesRepositoryDotusernameDotslugDotsettingsDotbranchProtectionDotrouteRoute
  '/$username/$slug/settings/status-providers': typeof modulesCheckStatusesRoutesRepositoryDotusernameDotslugDotsettingsDotstatusProvidersDotrouteRoute
  '/$username/$slug/settings/collaborators': typeof modulesRepositoryCollaboratorsRoutesRepositoryDotusernameDotslugDotsettingsDotcollaboratorsDotrouteRoute
  '/$username/$slug/blob/$ref/$': typeof modulesRepositoriesRoutesRepositoryDotusernameDotslugDotblobDotrefDotDotrouteRoute
  '/$username/$slug/pulls/$number/commits': typeof modulesPullRequestsRoutesRepositoryDotusernameDotslugDotpullsDotnumberDotcommitsDotrouteRoute
  '/$username/$slug/pulls/$number/files': typeof modulesPullRequestsRoutesRepositoryDotusernameDotslugDotpullsDotnumberDotfilesDotrouteRoute
  '/$username/$slug/tree/$ref/$': typeof modulesRepositoriesRoutesRepositoryDotusernameDotslugDottreeDotrefDotDotrouteRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof modulesHomeRoutesIndexDotrouteRoute
  '/import': typeof modulesGithubImportRoutesImportDotrouteRouteWithChildren
  '/profile': typeof modulesProfileRoutesProfileDotrouteRouteWithChildren
  '/$username/$slug': typeof modulesRepositoriesRoutesRepositoryDotusernameDotslugDotrouteRoute
  '/import/github': typeof modulesGithubImportRoutesImportDotgithubDotrouteRoute
  '/profile/$username': typeof modulesProfileRoutesProfileDotusernameDotrouteRoute
  '/$username/$slug/pulls': typeof modulesPullRequestsRoutesRepositoryDotusernameDotslugDotpullsDotrouteRoute
  '/api/auth/$': typeof modulesAuthRoutesApiDotauthDotDotrouteRoute
  '/$username/$slug/commits/$ref': typeof modulesRepositoriesRoutesRepositoryDotusernameDotslugDotcommitsDotrefDotrouteRoute
  '/$username/$slug/pulls/$number': typeof modulesPullRequestsRoutesRepositoryDotusernameDotslugDotpullsDotnumberDotrouteRoute
  '/$username/$slug/pulls/new': typeof modulesPullRequestsRoutesRepositoryDotusernameDotslugDotpullsDotnewDotrouteRoute
  '/$username/$slug/settings/branch-protection': typeof modulesBranchProtectionRoutesRepositoryDotusernameDotslugDotsettingsDotbranchProtectionDotrouteRoute
  '/$username/$slug/settings/status-providers': typeof modulesCheckStatusesRoutesRepositoryDotusernameDotslugDotsettingsDotstatusProvidersDotrouteRoute
  '/$username/$slug/settings/collaborators': typeof modulesRepositoryCollaboratorsRoutesRepositoryDotusernameDotslugDotsettingsDotcollaboratorsDotrouteRoute
  '/$username/$slug/blob/$ref/$': typeof modulesRepositoriesRoutesRepositoryDotusernameDotslugDotblobDotrefDotDotrouteRoute
  '/$username/$slug/pulls/$number/commits': typeof modulesPullRequestsRoutesRepositoryDotusernameDotslugDotpullsDotnumberDotcommitsDotrouteRoute
  '/$username/$slug/pulls/$number/files': typeof modulesPullRequestsRoutesRepositoryDotusernameDotslugDotpullsDotnumberDotfilesDotrouteRoute
  '/$username/$slug/tree/$ref/$': typeof modulesRepositoriesRoutesRepositoryDotusernameDotslugDottreeDotrefDotDotrouteRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/import'
    | '/profile'
    | '/$username/$slug'
    | '/import/github'
    | '/profile/$username'
    | '/$username/$slug/pulls'
    | '/api/auth/$'
    | '/$username/$slug/commits/$ref'
    | '/$username/$slug/pulls/$number'
    | '/$username/$slug/pulls/new'
    | '/$username/$slug/settings/branch-protection'
    | '/$username/$slug/settings/status-providers'
    | '/$username/$slug/settings/collaborators'
    | '/$username/$slug/blob/$ref/$'
    | '/$username/$slug/pulls/$number/commits'
    | '/$username/$slug/pulls/$number/files'
    | '/$username/$slug/tree/$ref/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/import'
    | '/profile'
    | '/$username/$slug'
    | '/import/github'
    | '/profile/$username'
    | '/$username/$slug/pulls'
    | '/api/auth/$'
    | '/$username/$slug/commits/$ref'
    | '/$username/$slug/pulls/$number'
    | '/$username/$slug/pulls/new'
    | '/$username/$slug/settings/branch-protection'
    | '/$username/$slug/settings/status-providers'
    | '/$username/$slug/settings/collaborators'
    | '/$username/$slug/blob/$ref/$'
    | '/$username/$slug/pulls/$number/commits'
    | '/$username/$slug/pulls/$number/files'
    | '/$username/$slug/tree/$ref/$'
  id:
    | '__root__'
    | '/'
    | '/import'
    | '/profile'
    | '/$username/$slug'
    | '/import/github'
    | '/profile/$username'
    | '/$username/$slug/pulls'
    | '/api/auth/$'
    | '/$username/$slug/commits/$ref'
    | '/$username/$slug/pulls/$number'
    | '/$username/$slug/pulls/new'
    | '/$username/$slug/settings/branch-protection'
    | '/$username/$slug/settings/status-providers'
    | '/$username/$slug/settings/collaborators'
    | '/$username/$slug/blob/$ref/$'
    | '/$username/$slug/pulls/$number/commits'
    | '/$username/$slug/pulls/$number/files'
    | '/$username/$slug/tree/$ref/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  modulesHomeRoutesIndexDotrouteRoute: typeof modulesHomeRoutesIndexDotrouteRoute
  modulesGithubImportRoutesImportDotrouteRoute: typeof modulesGithubImportRoutesImportDotrouteRouteWithChildren
  modulesProfileRoutesProfileDotrouteRoute: typeof modulesProfileRoutesProfileDotrouteRouteWithChildren
  modulesRepositoriesRoutesRepositoryDotusernameDotslugDotrouteRoute: typeof modulesRepositoriesRoutesRepositoryDotusernameDotslugDotrouteRoute
  modulesPullRequestsRoutesRepositoryDotusernameDotslugDotpullsDotrouteRoute: typeof modulesPullRequestsRoutesRepositoryDotusernameDotslugDotpullsDotrouteRoute
  modulesAuthRoutesApiDotauthDotDotrouteRoute: typeof modulesAuthRoutesApiDotauthDotDotrouteRoute
  modulesRepositoriesRoutesRepositoryDotusernameDotslugDotcommitsDotrefDotrouteRoute: typeof modulesRepositoriesRoutesRepositoryDotusernameDotslugDotcommitsDotrefDotrouteRoute
  modulesPullRequestsRoutesRepositoryDotusernameDotslugDotpullsDotnumberDotrouteRoute: typeof modulesPullRequestsRoutesRepositoryDotusernameDotslugDotpullsDotnumberDotrouteRoute
  modulesPullRequestsRoutesRepositoryDotusernameDotslugDotpullsDotnewDotrouteRoute: typeof modulesPullRequestsRoutesRepositoryDotusernameDotslugDotpullsDotnewDotrouteRoute
  modulesBranchProtectionRoutesRepositoryDotusernameDotslugDotsettingsDotbranchProtectionDotrouteRoute: typeof modulesBranchProtectionRoutesRepositoryDotusernameDotslugDotsettingsDotbranchProtectionDotrouteRoute
  modulesCheckStatusesRoutesRepositoryDotusernameDotslugDotsettingsDotstatusProvidersDotrouteRoute: typeof modulesCheckStatusesRoutesRepositoryDotusernameDotslugDotsettingsDotstatusProvidersDotrouteRoute
  modulesRepositoryCollaboratorsRoutesRepositoryDotusernameDotslugDotsettingsDotcollaboratorsDotrouteRoute: typeof modulesRepositoryCollaboratorsRoutesRepositoryDotusernameDotslugDotsettingsDotcollaboratorsDotrouteRoute
  modulesRepositoriesRoutesRepositoryDotusernameDotslugDotblobDotrefDotDotrouteRoute: typeof modulesRepositoriesRoutesRepositoryDotusernameDotslugDotblobDotrefDotDotrouteRoute
  modulesPullRequestsRoutesRepositoryDotusernameDotslugDotpullsDotnumberDotcommitsDotrouteRoute: typeof modulesPullRequestsRoutesRepositoryDotusernameDotslugDotpullsDotnumberDotcommitsDotrouteRoute
  modulesPullRequestsRoutesRepositoryDotusernameDotslugDotpullsDotnumberDotfilesDotrouteRoute: typeof modulesPullRequestsRoutesRepositoryDotusernameDotslugDotpullsDotnumberDotfilesDotrouteRoute
  modulesRepositoriesRoutesRepositoryDotusernameDotslugDottreeDotrefDotDotrouteRoute: typeof modulesRepositoriesRoutesRepositoryDotusernameDotslugDottreeDotrefDotDotrouteRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof modulesProfileRoutesProfileDotrouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/import': {
      id: '/import'
      path: '/import'
      fullPath: '/import'
      preLoaderRoute: typeof modulesGithubImportRoutesImportDotrouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof modulesHomeRoutesIndexDotrouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/$username': {
      id: '/profile/$username'
      path: '/$username'
      fullPath: '/profile/$username'
      preLoaderRoute: typeof modulesProfileRoutesProfileDotusernameDotrouteRouteImport
      parentRoute: typeof modulesProfileRoutesProfileDotrouteRoute
    }
    '/import/github': {
      id: '/import/github'
      path: '/github'
      fullPath: '/import/github'
      preLoaderRoute: typeof modulesGithubImportRoutesImportDotgithubDotrouteRouteImport
      parentRoute: typeof modulesGithubImportRoutesImportDotrouteRoute
    }
    '/$username/$slug': {
      id: '/$username/$slug'
      path: '/$username/$slug'
      fullPath: '/$username/$slug'
      preLoaderRoute: typeof modulesRepositoriesRoutesRepositoryDotusernameDotslugDotrouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof modulesAuthRoutesApiDotauthDotDotrouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$username/$slug/pulls': {
      id: '/$username/$slug/pulls'
      path: '/$username/$slug/pulls'
      fullPath: '/$username/$slug/pulls'
      preLoaderRoute: typeof modulesPullRequestsRoutesRepositoryDotusernameDotslugDotpullsDotrouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$username/$slug/settings/collaborators': {
      id: '/$username/$slug/settings/collaborators'
      path: '/$username/$slug/settings/collaborators'
      fullPath: '/$username/$slug/settings/collaborators'
      preLoaderRoute: typeof modulesRepositoryCollaboratorsRoutesRepositoryDotusernameDotslugDotsettingsDotcollaboratorsDotrouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$username/$slug/settings/branch-protection': {
      id: '/$username/$slug/settings/branch-protection'
      path: '/$username/$slug/settings/branch-protection'
      fullPath: '/$username/$slug/settings/branch-protection'
      preLoaderRoute: typeof modulesBranchProtectionRoutesRepositoryDotusernameDotslugDotsettingsDotbranchProtectionDotrouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$username/$slug/settings/status-providers': {
      id: '/$username/$slug/settings/status-providers'
      path: '/$username/$slug/settings/status-providers'
      fullPath: '/$username/$slug/settings/status-providers'
      preLoaderRoute: typeof modulesCheckStatusesRoutesRepositoryDotusernameDotslugDotsettingsDotstatusProvidersDotrouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$username/$slug/pulls/new': {
      id: '/$username/$slug/pulls/new'
      path: '/$username/$slug/pulls/new'
      fullPath: '/$username/$slug/pulls/new'
      preLoaderRoute: typeof modulesPullRequestsRoutesRepositoryDotusernameDotslugDotpullsDotnewDotrouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$username/$slug/pulls/$number': {
      id: '/$username/$slug/pulls/$number'
      path: '/$username/$slug/pulls/$number'
      fullPath: '/$username/$slug/pulls/$number'
      preLoaderRoute: typeof modulesPullRequestsRoutesRepositoryDotusernameDotslugDotpullsDotnumberDotrouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$username/$slug/commits/$ref': {
      id: '/$username/$slug/commits/$ref'
      path: '/$username/$slug/commits/$ref'
      fullPath: '/$username/$slug/commits/$ref'
      preLoaderRoute: typeof modulesRepositoriesRoutesRepositoryDotusernameDotslugDotcommitsDotrefDotrouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$username/$slug/tree/$ref/$': {
      id: '/$username/$slug/tree/$ref/$'
      path: '/$username/$slug/tree/$ref/$'
      fullPath: '/$username/$slug/tree/$ref/$'
      preLoaderRoute: typeof modulesRepositoriesRoutesRepositoryDotusernameDotslugDottreeDotrefDotDotrouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$username/$slug/pulls/$number/files': {
      id: '/$username/$slug/pulls/$number/files'
      path: '/$username/$slug/pulls/$number/files'
      fullPath: '/$username/$slug/pulls/$number/files'
      preLoaderRoute: typeof modulesPullRequestsRoutesRepositoryDotusernameDotslugDotpullsDotnumberDotfilesDotrouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$username/$slug/pulls/$number/commits': {
      id: '/$username/$slug/pulls/$number/commits'
      path: '/$username/$slug/pulls/$number/commits'
      fullPath: '/$username/$slug/pulls/$number/commits'
      preLoaderRoute: typeof modulesPullRequestsRoutesRepositoryDotusernameDotslugDotpullsDotnumberDotcommitsDotrouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$username/$slug/blob/$ref/$': {
      id: '/$username/$slug/blob/$ref/$'
      path: '/$username/$slug/blob/$ref/$'
      fullPath: '/$username/$slug/blob/$ref/$'
      preLoaderRoute: typeof modulesRepositoriesRoutesRepositoryDotusernameDotslugDotblobDotrefDotDotrouteRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface modulesGithubImportRoutesImportDotrouteRouteChildren {
  modulesGithubImportRoutesImportDotgithubDotrouteRoute: typeof modulesGithubImportRoutesImportDotgithubDotrouteRoute
}

const modulesGithubImportRoutesImportDotrouteRouteChildren: modulesGithubImportRoutesImportDotrouteRouteChildren =
  {
    modulesGithubImportRoutesImportDotgithubDotrouteRoute:
      modulesGithubImportRoutesImportDotgithubDotrouteRoute,
  }

const modulesGithubImportRoutesImportDotrouteRouteWithChildren =
  modulesGithubImportRoutesImportDotrouteRoute._addFileChildren(
    modulesGithubImportRoutesImportDotrouteRouteChildren,
  )

interface modulesProfileRoutesProfileDotrouteRouteChildren {
  modulesProfileRoutesProfileDotusernameDotrouteRoute: typeof modulesProfileRoutesProfileDotusernameDotrouteRoute
}

const modulesProfileRoutesProfileDotrouteRouteChildren: modulesProfileRoutesProfileDotrouteRouteChildren =
  {
    modulesProfileRoutesProfileDotusernameDotrouteRoute:
      modulesProfileRoutesProfileDotusernameDotrouteRoute,
  }

const modulesProfileRoutesProfileDotrouteRouteWithChildren =
  modulesProfileRoutesProfileDotrouteRoute._addFileChildren(
    modulesProfileRoutesProfileDotrouteRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  modulesHomeRoutesIndexDotrouteRoute: modulesHomeRoutesIndexDotrouteRoute,
  modulesGithubImportRoutesImportDotrouteRoute:
    modulesGithubImportRoutesImportDotrouteRouteWithChildren,
  modulesProfileRoutesProfileDotrouteRoute:
    modulesProfileRoutesProfileDotrouteRouteWithChildren,
  modulesRepositoriesRoutesRepositoryDotusernameDotslugDotrouteRoute:
    modulesRepositoriesRoutesRepositoryDotusernameDotslugDotrouteRoute,
  modulesPullRequestsRoutesRepositoryDotusernameDotslugDotpullsDotrouteRoute:
    modulesPullRequestsRoutesRepositoryDotusernameDotslugDotpullsDotrouteRoute,
  modulesAuthRoutesApiDotauthDotDotrouteRoute:
    modulesAuthRoutesApiDotauthDotDotrouteRoute,
  modulesRepositoriesRoutesRepositoryDotusernameDotslugDotcommitsDotrefDotrouteRoute:
    modulesRepositoriesRoutesRepositoryDotusernameDotslugDotcommitsDotrefDotrouteRoute,
  modulesPullRequestsRoutesRepositoryDotusernameDotslugDotpullsDotnumberDotrouteRoute:
    modulesPullRequestsRoutesRepositoryDotusernameDotslugDotpullsDotnumberDotrouteRoute,
  modulesPullRequestsRoutesRepositoryDotusernameDotslugDotpullsDotnewDotrouteRoute:
    modulesPullRequestsRoutesRepositoryDotusernameDotslugDotpullsDotnewDotrouteRoute,
  modulesBranchProtectionRoutesRepositoryDotusernameDotslugDotsettingsDotbranchProtectionDotrouteRoute:
    modulesBranchProtectionRoutesRepositoryDotusernameDotslugDotsettingsDotbranchProtectionDotrouteRoute,
  modulesCheckStatusesRoutesRepositoryDotusernameDotslugDotsettingsDotstatusProvidersDotrouteRoute:
    modulesCheckStatusesRoutesRepositoryDotusernameDotslugDotsettingsDotstatusProvidersDotrouteRoute,
  modulesRepositoryCollaboratorsRoutesRepositoryDotusernameDotslugDotsettingsDotcollaboratorsDotrouteRoute:
    modulesRepositoryCollaboratorsRoutesRepositoryDotusernameDotslugDotsettingsDotcollaboratorsDotrouteRoute,
  modulesRepositoriesRoutesRepositoryDotusernameDotslugDotblobDotrefDotDotrouteRoute:
    modulesRepositoriesRoutesRepositoryDotusernameDotslugDotblobDotrefDotDotrouteRoute,
  modulesPullRequestsRoutesRepositoryDotusernameDotslugDotpullsDotnumberDotcommitsDotrouteRoute:
    modulesPullRequestsRoutesRepositoryDotusernameDotslugDotpullsDotnumberDotcommitsDotrouteRoute,
  modulesPullRequestsRoutesRepositoryDotusernameDotslugDotpullsDotnumberDotfilesDotrouteRoute:
    modulesPullRequestsRoutesRepositoryDotusernameDotslugDotpullsDotnumberDotfilesDotrouteRoute,
  modulesRepositoriesRoutesRepositoryDotusernameDotslugDottreeDotrefDotDotrouteRoute:
    modulesRepositoriesRoutesRepositoryDotusernameDotslugDottreeDotrefDotDotrouteRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
