name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  lint:
    name: 'Check 🐱'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎
        uses: actions/checkout@master

      - name: Setup 👨🏻‍💻
        uses: ./.github/actions/setup

      - name: Check JS files 🐱
        run: bun run check

  typecheck:
    name: 'Typecheck 🔍'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎
        uses: actions/checkout@master

      - name: Setup 👨🏻‍💻
        uses: ./.github/actions/setup

      - name: Typecheck 🔍
        run: bun run typecheck

  build:
    name: 'Build 🏗'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎
        uses: actions/checkout@master

      - name: Setup 👨🏻‍💻
        uses: ./.github/actions/setup

      - name: Build 🏗
        run: bun run build

  unit-tests:
    name: 'Unit Tests 🧪'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout 🛎
        uses: actions/checkout@master

      - name: Setup 👨🏻‍💻
        uses: ./.github/actions/setup

      - name: Unit Tests 🧪
        run: bun run test

  integration-tests:
    name: 'Integration Tests 🧪'
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_USER: test
          POSTGRES_PASSWORD: test
          POSTGRES_DB: tessera_test
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U test -d tessera_test"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - name: Checkout 🛎
        uses: actions/checkout@master

      - name: Setup 👨🏻‍💻
        uses: ./.github/actions/setup

      - name: API Integration Tests 🧪
        env:
          DATABASE_URL: postgresql://test:test@localhost:5432/tessera_test
        run: bun run --filter @repo/api test:integration
