name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  lint:
    name: 'Check 🐱'
    runs-on: blacksmith-4vcpu-ubuntu-2204
    steps:
      - name: Checkout 🛎
        uses: actions/checkout@master

      - name: Setup 👨🏻‍💻
        uses: ./.github/actions/setup

      - name: Check JS files 🐱
        run: bun run check

  typecheck:
    name: 'Typecheck 🔍'
    runs-on: blacksmith-4vcpu-ubuntu-2204
    steps:
      - name: Checkout 🛎
        uses: actions/checkout@master

      - name: Setup 👨🏻‍💻
        uses: ./.github/actions/setup

      - name: Typecheck 🔍
        run: bun run typecheck

  build:
    name: 'Build 🏗'
    runs-on: blacksmith-4vcpu-ubuntu-2204
    steps:
      - name: Checkout 🛎
        uses: actions/checkout@master

      - name: Setup 👨🏻‍💻
        uses: ./.github/actions/setup

      - name: Build 🏗
        run: bun run build

  unit-tests:
    name: 'Unit Tests 🧪'
    runs-on: blacksmith-4vcpu-ubuntu-2204

    steps:
      - name: Checkout 🛎
        uses: actions/checkout@master

      - name: Setup 👨🏻‍💻
        uses: ./.github/actions/setup

      - name: Unit Tests (Web & UI) 🧪
        run: bun run test --filter @repo/web --filter @repo/ui

      - name: Unit Tests (API) 🧪
        run: bun run test --force --filter @repo/api -- --coverage

      - name: Upload API coverage report to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          flags: api
          working-directory: ./apps/api

  integration-tests:
    name: 'Integration Tests 🧪'
    runs-on: blacksmith-4vcpu-ubuntu-2204
    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_USER: test
          POSTGRES_PASSWORD: test
          POSTGRES_DB: tessera_test
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U test -d tessera_test"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - name: Checkout 🛎
        uses: actions/checkout@master

      - name: Setup 👨🏻‍💻
        uses: ./.github/actions/setup

      - name: API Integration Tests 🧪
        env:
          DATABASE_URL: postgresql://test:test@localhost:5432/tessera_test
        run: bun run --filter @repo/api test:integration
